services:
  - type: web
    name: chereta-api
    runtime: elixir
    buildCommand: "./build.sh"
    startCommand: "_build/prod/rel/chereta/bin/chereta start"
    plan: free
    env: production
    buildFilter:
      paths:
      - lib/**
      - config/**
      - mix.exs
      - mix.lock
    envVars:
      # Neon Database Configuration
      - key: DB_USERNAME
        value: neondb_owner
      - key: DB_PASSWORD
        value: npg_bHKdIrTjq3G9
      - key: DB_HOSTNAME
        value: ep-long-leaf-a5pdirxg-pooler.us-east-2.aws.neon.tech
      - key: DB_DATABASE
        value: neondb
      - key: DB_PORT
        value: 5432
      # Phoenix Configuration
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: PHX_HOST
        fromService:
          type: web
          name: chereta-api
          property: host
      - key: PORT
        value: 4000
      - key: PHX_SERVER
        value: "true"
      - key: MIX_ENV
        value: prod
      - key: POOL_SIZE
        value: 10

# Note: Removed databases section since we're using external Neon database