import Config

# Load environment variables from .env file in development (WSL compatible)
env_file = Path.join([__DIR__, "..", ".env"])
if File.exists?(env_file) do
  File.stream!(env_file)
  |> Stream.map(&String.trim/1)
  |> Stream.reject(&String.starts_with?(&1, "#"))
  |> Stream.reject(&(&1 == ""))
  |> Stream.map(&String.split(&1, "=", parts: 2))
  |> Stream.filter(&(length(&1) == 2))
  |> Enum.each(fn [key, value] ->
    cleaned_value = value |> String.trim() |> String.trim_leading("\"") |> String.trim_trailing("\"")
    System.put_env(key, cleaned_value)
  end)
end

# Configure your database
config :chereta, Chereta.Repo,
  username: System.get_env("DB_USERNAME"),
  password: System.get_env("DB_PASSWORD"),
  hostname: System.get_env("DB_HOSTNAME"),
  database: System.get_env("DB_DATABASE"),
  port: String.to_integer(System.get_env("DB_PORT") || "5432"),
  ssl: [verify: :verify_none],
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10,
  timeout: 60_000,
  ownership_timeout: 60_000,
  queue_target: 5_000,
  queue_interval: 10_000

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :chereta, CheretaWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {0, 0, 0, 0}, port: 4002],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "jvIB8wMwxQ4YMASnS7m0wBwdHJj4/T4RslTpUca0lNrs1T5XGQ+ZwjD//blnnhG2",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :chereta, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
